// Generated by https://quicktype.io

export interface UsersInterfaces {
    name:       string;
    email:      string;
    customer:   string;
    path:       string[];
    updated_at: string;
    created_at: string;
}
