// Generated by https://quicktype.io

export interface Insights {
    insights:         InsightsClass;
    summary:          Summary;
    assets_analytics: AssetsAnalytic[];
    geo_data:         GeoDatum[];
}

export interface AssetsAnalytic {
    class:      string;
    value:      number;
    total:      number;
    percentage: number;
}

export interface GeoDatum {
    area:        string;
    num_coolers: number;
    latitude:    number;
    longitude:   number;
}

export interface InsightsClass {
    ALERT:     Alert;
    FAIL:      Alert;
    INDICATOR: Alert;
    NO_FAIL:   Alert;
}

export interface Alert {
    level:      Level;
    total:      number;
    algorithms: Algorithm[];
}

export interface Algorithm {
    level:     Level;
    class:     string;
    algorithm: string;
    value:     number;
}

export enum Level {
    Alert = "ALERT",
    Fail = "FAIL",
    Indicator = "INDICATOR",
    NoFail = "NO_FAIL",
}

export interface Summary {
    coolers:         number;
    zones:           number;
    regions:         number;
    operative_units: number;
    routes:          number;
}
